---
- hosts: 192.168.4.140
  remote_user: root
  vars:
  - REGISTRY: registry.develop.asiacom.net.cn/develop
  - image_name: oem-cmp
  - TAG: 3.1.10
  - container_name: oem

  pre_tasks:
  - name: install epel-release
    yum: name=epel-release state=present
    when: ansible_os_family ==  "RedHat"

  tasks:
    - name: ping baidu.com
      shell: ping -c 3 -w 3 www.baidu.com

- hosts: 192.168.4.233
  remote_user: root
  vars:
  - REGISTRY: registry.develop.asiacom.net.cn/develop
  - image_name: oem-cmp
  - TAG: 3.1.10
  - container_name: oem

  pre_tasks:
  - name: install epel-release
    yum: name=epel-release state=present
    when: ansible_os_family ==  "RedHat"

  tasks:
    - name: ping baidu.com
      shell: ping -c 3 -w 3 www.baidu.com & echo ${REGISTRY}